### ISSUE TITLE
Manual BS version selection

### ISSUE THREAD

**Issue by stalker780** [aviiceena/bootstrap-intellisense#14]
Is there a way to manually select BS version for the project/folder?
I am working with OpenCart4 and extension detects BS4.5, while BS5.3 is used in templates.
It suggests me .float-left class instead of .float-start and other things from BS4.5

**Comment by hossaini310** [comment]
Are you using bootstrap 4.5 anywhere in your project? because actually it takes the bootstrap version from node modules or from index.html

**Comment by stalker780** [comment]
Nope. Only BS 5.3.3.

https://github.com/opencart/opencart

**Comment by hossaini310** [comment]
I uploaded a new version 1.5.0 today, see if you still have the problem

**Comment by stalker780** [comment]
@hossaini310 Was Bootstrap 4.5 now shows Bootstrap 4.5.3 in the status bar.
Nothing changed so far.

**Comment by hossaini310** [comment]
Unfortunately, I don't know why it isn't displayed correctly for you.
Maybe you can test it in a new project.

For me, the version that I use in my project is displayed correctly.

**Comment by stalker780** [comment]
As far as I understand your extension cannot recognize bs styles connected in php or twig files.

OC4:
https://github.com/opencart/opencart/blob/72cdae5b3288b148b24fa7bd53a617b5445c34ab/upload/catalog/controller/common/header.php#L37

or OC3, this one does not detect BS version at all
https://github.com/opencart/opencart/blob/f7006bf771fd59250c6724bdea2f81d83dbf03cf/upload/catalog/view/theme/default/template/common/header.twig#L21

That's sad. I have checked several extensions and liked yours the most. But alas it does not detect correct bs version.

As I mentioned before, perhaps you could plan a manual bs version selection for a project. This would solve this problem.

Anyway, thanks for your effort.

**Comment by hossaini310** [comment]
Thank you. I will look for a solution and then let you know

**Comment by aviiceena** [comment]
You can now select the bootstrap version manually. This should solve your problem

**Comment by stalker780** [comment]
@aviiceena Thanks!
Works like a charm now 👍
