### ISSUE TITLE
Available in blade.php

### ISSUE THREAD

**Issue by hariirawan** [aviiceena/bootstrap-intellisense#17]
Bootstrap intellisense works fine for me in html files. but, it doesn't work in blade.php. Is there a way to enable this extension in the .blade.php file?
![Screenshot 2024-07-14 at 22 28 39](https://github.com/user-attachments/assets/6068e3db-b699-4780-a51e-dd3818eebeeb)

**Comment by Emad-am** [comment]
i have the same problem with blade.php files

**Comment by hossaini310** [comment]
How do you use Bootstrap in your project? CDN, locale file or node_modules?

**Comment by Emad-am** [comment]
i have tried it with CDN and local. non of it worked

**Comment by aviiceena** [comment]
You can now select the bootstrap version manually. This should solve your problem
