### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Raja-Battula369** [aviiceena/bootstrap-intellisense#18]
- Issue Type: `Performance`
- Extension Name: `bootstrap-intellisense`
- Extension Version: `1.5.3`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.91.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/oddey/AppData/Local/Temp/hossaini.bootstrap-intellisense-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by aviiceena** [comment]
This should be fixed now. The code has now become simpler and less. Make sure you have the latest version (v2.0.1)
