### ISSUE TITLE
Use CDN as fallback when no local copies of Bootstrap can be found

### ISSUE THREAD

**Issue by ChrisMBarr** [aviiceena/bootstrap-intellisense#27]
I have an Angular project, and I'm using SCSS to build a custom version of Bootstrap locally.

In Angular projects it handles the SCSS compilation for you. Just tell it the paths to the files you want in the `angular.json` file and it handles the linking for you.

Upon compilation, it combines all of those files into a single CSS file, which looks like this
![image](https://github.com/user-attachments/assets/4031a2f4-3575-44ea-9c5d-f4e41e9c9625)

That file doesn't actually exist on disk anywhere, and it's not linked to manually in any HTML template.

So... all that to say I am using Bootstrap, but I have no `.css` file that this plugin can find. I need a way to just be able to use this plugin. Can it just try to use a generic version of Bootstrap as a fallback when it can't find anything?  Like, just grab the latest version from a CDN as a worst case scenerio.

**Comment by aviiceena** [comment]
I'm currently working on a new version where you can select the bootstrap version yourself with a dropdown menu. Hopefully this can solve your problem.

**Comment by aviiceena** [comment]
The new version is out now.

**Comment by aviiceena** [comment]
The new version is out now.
