### ISSUE TITLE
Add support for .lava files 

### ISSUE THREAD

**Issue by Andrew-Forster** [aviiceena/bootstrap-intellisense#34]
Please consider adding support for .lava files. You can reference it here, shouldn't be hard.

https://community.rockrms.com/

OR

Add issue https://github.com/aviiceena/bootstrap-intellisense/issues/32

**Comment by aviiceena** [comment]
Hi, I added now lava in language support list. (v2.0.2)

**Comment by Andrew-Forster** [comment]
Thank you, but I'm not sure it's working. I have the latest version and restarted my extensions. is anyone able to confirm this?

**Comment by aviiceena** [comment]
Can you send me some example code?

**Comment by Andrew-Forster** [comment]
Never mind it does work! For some reason it was off by default for vscode!
